#!/bin/bash
#
# kolmnurk vasakult paremale
#
for ((r=5; r>0; r--))
do
	# trükime reanumbri ilma reavahetuseta
	#echo -n "$r"
	for ((v=1; v<=$r+1; v++))
	do
	echo -n "* "
	done
	# kui rida lõpeb - reavahetus
	echo
done
