#!/bin/bash
#
# Kasutaja tervitus vastavalt sisestatud väärtusele

echo -n "Sisestage palun kellaaeg 6-24: "
read kellaaeg

if [ $kellaaeg -ge 6 -a $kellaaeg -lt 12 ]; then
		echo "Tere hommikust!"
	elif [ $kellaaeg -ge 12 -a $kellaaeg -lt 18 ]; then
		echo "Tere päevast!"
	elif [ $kellaaeg -ge 18 -a $kellaaeg -lt 22 ]; then
		echo "Tere õhtust!"
	elif [ $kellaaeg -ge 22 -a $kellaaeg -lt 24 ]; then
		echo "Head ööd!"
	elif [ $kelllaaeg -ge 0 -a $kellaaeg -lt 6 ]; then
		echo "Head ööd!"
	else 
	echo "Vale number"
fi

