#!/bin/bash
#
# muutujate kasutamise näide
#
#defineerime muutuja ja omistame väärtus
#väärtus saadalse whoami käsust
kasutaja=`whoami`
#väljastame muutuja väärtus koos seletusega
echo "Tere, $kasutaja"
