#!/bin/bash
#
# arvu positiivsuse/negatiivsuse
# küsime väärtused kasutaja käest
#kontrllime, kas kasutaja sissesta käsurea kaudu 1 parametri
#kui mitte - trükime kasutusjuhend välja
if [ $# -ne 1 ]; then
echo "Kasutaja juhend"
echo "$0 number"
echo "naiteks $0 5"
else
arv=$1
#kontrollime, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 1 ]
then
    echo "$arv on positiivne"
elif [ $arv -lt 0 ]
then
    echo "$arv on negatiivne"
else
    echo  "$arv on netraalne"
fi
fi



