#!/bin/bash
# Nimi: Artur Aleksejev
# Skripti nimi: menu
# Skripti ülesanne: Väljastada vastavalt rida mida kasutaja valis


echo "Valige menüüst:"
echo "1) steak and potatoes"
echo "2) fish and chips"
echo "3) soup and salad"
echo
echo "Please make a selection (1 or 2 or 3)"
read s

if [ $s -eq 1 ]; then
	echo "Stick to your ribs."
	echo "Watch your cholesterol."
	echo "Enjoy your meal!"

elif [ $s -eq 2 ]; then
	echo "British are coming!"
	echo "Enjoy your meal!"

elif [ $s -eq 3 ]; then
	echo "Health foods..."
	echo "Dieting is so boring"
	echo "Enjoy your meal!"
fi
